### ISSUE TITLE
qmake Project ERROR: libseafile development package not found

### ISSUE THREAD

**Issue by ghost** [Skycoder42/dolphin-seafile-plugin#3]
Can't build it.
When I run qmake in the plugin directory it says
`Project ERROR: libseafile development package not found`

Apt output:
```
$ apt policy libseafile-dev  
libseafile-dev:  
  Installed: 6.2.9-2~1290~ubuntu18.10.1  
  Candidate: 6.2.9-2~1290~ubuntu18.10.1  
  Version table:  
 *** 6.2.9-2~1290~ubuntu18.10.1 500  
        500 http://ppa.launchpad.net/seafile/seafile-client/ubuntu cosmic/main amd64 Packages  
        100 /var/lib/dpkg/status  
     6.2.4-1 500  
        500 http://de.archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages  
```

OS: Kubuntu 18.10
Seafile client version: 6.2.9

**Comment by Skycoder42** [comment]
The plugin requires a pkgconfig file for seafile (See [plugin.pro](https://github.com/Skycoder42/dolphin-seafile-plugin/blob/master/plugin/plugin.pro#L8)). This error probably means that your distro does not come with one or that it is located in a different package.

The pc file is part of seafile upstream, which means if it is missing, the package maintainers of your distro decided to for whatever reason exclude it. As a workaround, you can just remove the line and instead manually link against the library.

**Comment by ghost** [comment]
```
$ apt list --installed | grep seafile   
libseafile-dev/cosmic,now 6.2.9-2~1290~ubuntu18.10.1 amd64 [installed]  
libseafile0/cosmic,now 6.2.9-2~1290~ubuntu18.10.1 amd64 [installed,automatic]  
seafile-daemon/cosmic,now 6.2.9-2~1290~ubuntu18.10.1 amd64 [installed]  
seafile-gui/cosmic,now 6.2.9-2~1512~ubuntu18.10.1 amd64 [installed]  
```

Can I just change that line to libseafile0 or is that not the needed thing?

Edit: no I can't.


How do I manually link against the library?

**Comment by Skycoder42** [comment]
Okay, so I just checked the packages online (See https://packages.ubuntu.com/cosmic/amd64/libseafile-dev/filelist) and at least theoretically, the pkgconfig file should be on your system. Please check if that file exists and verify it's contents.

If the file is there, please try to run qmake with the path explicitly set:
```
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig qmake
```

If that still does not work, I can find out what the explicitly link lines are

**Comment by Skycoder42** [comment]
Also, please install `libsearpc-dev` as well! It is needed as well

**Comment by ghost** [comment]
The pkgconfig file is not there.
I'll try fixing this first.

Oh I see, the file list you linked is for version 6.2.4-1 while the version that is automatically picked for me is 6.2.9-2 - I checked that version and it doesn't have the pkgconfig file.
As you can see in the apt policy in my original post, its from a PPA, that is suggested on  [seafile website](https://help.seafile.com/en/syncing_client/install_linux_client.html)

Edit: 
Installing the slightly older version from Ubuntu repos fixed this issue.
I am not sure what you can do, but I suggest at least mentioning somewhere that installing from seafile's PPA does not work. Maybe there is a workaround. 

Thanks for your help!

**Comment by Skycoder42** [comment]
I just checked that PPA as well, and the pc files are indeed present in those as well! (See https://code.launchpad.net/~seafile/+archive/ubuntu/seafile-client/+packages)

The only difference is the location - it is `/usr/lib/pkgconfig` - which means to use this PPA, simply run qmake as:
```
PKG_CONFIG_PATH=/usr/lib/pkgconfig qmake
```
