### ISSUE TITLE
Kubuntu18.10 make fatal error missing packages

### ISSUE THREAD

**Issue by ghost** [Skycoder42/dolphin-seafile-plugin#4]
Here is a list of packages that need to be installed in order to make the project successfully:

libdolphinvcs-dev
libsearpc-dev
libglib2.0-dev

After installing libglib2.0-dev one needs to run
`pkg-config --cflags --libs glib-2.0`
and add the output to the makefile's INCPATH

**Comment by Skycoder42** [comment]
Packages are platform- and distro-dependend. when `pkgconfig` is working correctly, those dependencies are automatically detected.

Also, the fix with the flags should not be neccessary with pkgconfig, as those flags etc. should be added automatically. Again, something seems to be wrong with your pkgconfig...
